import { Category, Product, Property, DigitalBook, Course, Banner, Voucher, Testimonial, SiteSettings } from "./types";

export const initialSiteSettings: SiteSettings = {
  site_name: "Karobaari Hub & Prism Real Estate",
  hotline: "+92 335 9939 702",
  whatsapp: "+92 335 9939 702",
  email: "prismrealestate4@gmail.com",
  address: "Shahpur, Adyala Road, Rawalpindi / Islamabad",
  free_shipping_threshold: 3000,
  standard_shipping_fee: 199,
  coins_discount_rate: 0.05,
  cod_enabled: true,
  jazzcash_number: "0335 9939702",
  jazzcash_title: "Karobaari Hub",
  easypaisa_number: "0335 9939702",
  easypaisa_title: "Karobaari Hub",
  bank_name: "Meezan Bank Limited",
  bank_account_title: "Karobaari Hub & Prism Real Estate",
  bank_account_number: "PK45MEZN0001234567890101",
};

export const initialCategories: Category[] = [
  {
    id: "cat-1",
    name: "Mobiles & Tablets",
    slug: "mobiles-tablets",
    description: "Smartphones, tablets, power banks, chargers and mobile accessories",
    icon: "Smartphone",
    image_url: "/assets/ecommerce-banner-1.jpeg",
    is_active: true,
    sort_order: 1,
  },
  {
    id: "cat-2",
    name: "Electronic Accessories",
    slug: "electronic-accessories",
    description: "Smart watches, earbuds, headphones, cables and Bluetooth speakers",
    icon: "Headphones",
    image_url: "/assets/ecommerce-banner-2.jpeg",
    is_active: true,
    sort_order: 2,
  },
  {
    id: "cat-3",
    name: "TV, Audio & Home Appliances",
    slug: "tv-audio-appliances",
    description: "TVs, speakers, kitchen gadgets and home appliances",
    icon: "Tv",
    image_url: "/assets/ecommerce-banner-1.jpeg",
    is_active: true,
    sort_order: 3,
  },
  {
    id: "cat-4",
    name: "Men's Fashion",
    slug: "mens-fashion",
    description: "Clothing, shoes, wallets, belts and watches",
    icon: "Shirt",
    image_url: "/assets/ecommerce-banner-2.jpeg",
    is_active: true,
    sort_order: 4,
  },
  {
    id: "cat-5",
    name: "Women's Fashion",
    slug: "womens-fashion",
    description: "Stitched & unstitched suits, jewelry, handbags and footwear",
    icon: "Sparkles",
    image_url: "/assets/ecommerce-banner-1.jpeg",
    is_active: true,
    sort_order: 5,
  },
  {
    id: "cat-6",
    name: "Health & Beauty",
    slug: "health-beauty",
    description: "Skincare, haircare, fragrances, personal care and trimmers",
    icon: "HeartPulse",
    image_url: "/assets/ecommerce-banner-2.jpeg",
    is_active: true,
    sort_order: 6,
  },
  {
    id: "cat-7",
    name: "Home & Lifestyle",
    slug: "home-lifestyle",
    description: "Decor, organizers, kitchen tools, bedding and storage stands",
    icon: "Home",
    image_url: "/assets/ecommerce-banner-1.jpeg",
    is_active: true,
    sort_order: 7,
  },
  {
    id: "cat-8",
    name: "Groceries & Pets",
    slug: "groceries-pets",
    description: "Daily essentials, household consumables and pet care",
    icon: "ShoppingBag",
    image_url: "/assets/ecommerce-banner-2.jpeg",
    is_active: true,
    sort_order: 8,
  },
  {
    id: "cat-9",
    name: "Baby, Kids & Toys",
    slug: "baby-kids-toys",
    description: "Toys, baby care, kids clothing and educational kits",
    icon: "Baby",
    image_url: "/assets/ecommerce-banner-1.jpeg",
    is_active: true,
    sort_order: 9,
  },
  {
    id: "cat-10",
    name: "Sports & Outdoor",
    slug: "sports-outdoor",
    description: "Fitness, gym gear, outdoor equipment and sports items",
    icon: "Activity",
    image_url: "/assets/ecommerce-banner-2.jpeg",
    is_active: true,
    sort_order: 10,
  },
  {
    id: "cat-11",
    name: "Automotive & Motorbike",
    slug: "automotive-motorbike",
    description: "Car & bike accessories, helmets, gadgets and cleaning kits",
    icon: "Car",
    image_url: "/assets/ecommerce-banner-1.jpeg",
    is_active: true,
    sort_order: 11,
  },
  {
    id: "cat-12",
    name: "Stationery & Office Supplies",
    slug: "stationery-office",
    description: "Pens, notebooks, desk accessories and office supplies",
    icon: "BookOpen",
    image_url: "/assets/ecommerce-banner-2.jpeg",
    is_active: true,
    sort_order: 12,
  },
];

export const initialBanners: Banner[] = [
  {
    id: "banner-1",
    title: "Karobaari Hub Mega Summer Clearance",
    subtitle: "Up to 70% Off on Electronics, Fashion & Home Essentials",
    image_url: "/assets/ecommerce-banner-1.jpeg",
    mobile_image_url: "/assets/ecommerce-banner-1.jpeg",
    link_url: "/shop",
    cta_text: "Shop Flash Sale",
    bg_gradient: "from-maroon to-darkMaroon",
    sort_order: 1,
    is_active: true,
  },
  {
    id: "banner-2",
    title: "Prism Real Estate — Prime Properties For Sale",
    subtitle: "Houses & Plots on Adyala Road, DHA, Bahria Town Rawalpindi",
    image_url: "/assets/real-estate-banner-1.jpeg",
    mobile_image_url: "/assets/real-estate-banner-1.jpeg",
    link_url: "/real-estate",
    cta_text: "Explore Properties",
    bg_gradient: "from-darkMaroon to-darkGray",
    sort_order: 2,
    is_active: true,
  },
  {
    id: "banner-3",
    title: "High-Speed Sublimation & Printing Press Machines",
    subtitle: "Commercial Grade Equipment with Local Warranty & Free Setup",
    image_url: "/assets/ecommerce-banner-2.jpeg",
    mobile_image_url: "/assets/ecommerce-banner-2.jpeg",
    link_url: "/shop/electronic-accessories",
    cta_text: "View Equipment",
    bg_gradient: "from-maroon to-black",
    sort_order: 3,
    is_active: true,
  },
  {
    id: "banner-4",
    title: "Build Your Digital Business — Online Courses & E-Books",
    subtitle: "Practical Masterclasses with Lifetime Access & Direct Mentorship",
    image_url: "/assets/real-estate-banner-2.jpeg",
    mobile_image_url: "/assets/real-estate-banner-2.jpeg",
    link_url: "/courses",
    cta_text: "Enroll Today",
    bg_gradient: "from-darkGray to-maroon",
    sort_order: 4,
    is_active: true,
  },
  {
    id: "banner-5",
    title: "Brand New 4 Marla 1.5 Story House in Shahpur",
    subtitle: "Rs. 1 Crore 20 Lakh — 3 Beds, 2 Kitchens, 30 Ft Street",
    image_url: "/assets/real-estate-banner-1.jpeg",
    mobile_image_url: "/assets/real-estate-banner-1.jpeg",
    link_url: "/real-estate/property/4-marla-brand-new-house-shahpur",
    cta_text: "Book A Visit",
    bg_gradient: "from-darkMaroon to-gold",
    sort_order: 5,
    is_active: true,
  },
  {
    id: "banner-6",
    title: "Daily Sasti Choice — Unbeatable Everyday Prices",
    subtitle: "Authentic Goods Delivered Straight To Your Doorstep",
    image_url: "/assets/ecommerce-banner-1.jpeg",
    mobile_image_url: "/assets/ecommerce-banner-1.jpeg",
    link_url: "/shop",
    cta_text: "Discover Deals",
    bg_gradient: "from-maroon to-darkGray",
    sort_order: 6,
    is_active: true,
  },
];

export const initialVouchers: Voucher[] = [
  {
    id: "vouch-1",
    code: "WELCOME30",
    title: "30% OFF First Order",
    discount_type: "percentage",
    discount_value: 30,
    min_spend: 1500,
    max_discount: 1000,
    is_free_shipping: false,
    is_active: true,
  },
  {
    id: "vouch-2",
    code: "FREESHIP450",
    title: "Rs. 450 Free Shipping Voucher",
    discount_type: "fixed",
    discount_value: 450,
    min_spend: 2500,
    is_free_shipping: true,
    is_active: true,
  },
  {
    id: "vouch-3",
    code: "KAROBAARI10",
    title: "10% Flat Discount Voucher",
    discount_type: "percentage",
    discount_value: 10,
    min_spend: 3000,
    max_discount: 2000,
    is_free_shipping: false,
    is_active: true,
  },
];

export const initialProducts: Product[] = [
  {
    id: "prod-1",
    name: "Cloth Hanging Stand with Shoe Shelf & Heavy Duty Frame",
    slug: "cloth-hanging-stand-shoe-shelf",
    category_id: "cat-7",
    category_name: "Home & Lifestyle",
    category_slug: "home-lifestyle",
    brand_name: "Karobaari Home",
    short_description: "Multi-purpose double shoe rack with side hooks and high load capacity.",
    description: "Keep your room organized with this robust stainless steel double clothes rack with integrated shoe storage shelf. Easy assembly and smooth glide wheels.",
    price: 3200,
    sale_price: 2619,
    sku: "KB-CHS-001",
    stock: 45,
    thumbnail_url: "/assets/ecommerce-banner-1.jpeg",
    is_active: true,
    is_featured: true,
    is_flash_sale: true,
    flash_sale_end: new Date(Date.now() + 86400000 * 2).toISOString(),
    rating: 4.8,
    review_count: 32,
    sales_count: 142,
    location_tag: "Punjab",
    variants: [
      { id: "var-1", product_id: "prod-1", name: "Single Shelf - Black", attributes: { color: "Black", tier: "Single" }, price: 3200, sale_price: 2619, stock: 25, is_active: true },
      { id: "var-2", product_id: "prod-1", name: "Double Shelf - White", attributes: { color: "White", tier: "Double" }, price: 3800, sale_price: 3199, stock: 20, is_active: true },
    ],
    specifications: {
      "Material": "Carbon Steel + PP Connectors",
      "Dimensions": "150cm x 110cm x 40cm",
      "Weight Capacity": "40 KG",
      "Warranty": "7 Days Replacement Warranty"
    }
  },
  {
    id: "prod-2",
    name: "Commercial Sublimation Heat Press Machine for T-Shirts & Mugs",
    slug: "sublimation-heat-press-machine-5-in-1",
    category_id: "cat-2",
    category_name: "Electronic Accessories",
    category_slug: "electronic-accessories",
    brand_name: "Karobaari Pro",
    short_description: "5-in-1 combo heat press for mugs, t-shirts, caps, and plates.",
    description: "Professional digital heat press machine with accurate temperature controller, 360-degree swing-away design, and Teflon-coated heating element.",
    price: 48000,
    sale_price: 41500,
    sku: "KB-SUB-5IN1",
    stock: 12,
    thumbnail_url: "/assets/ecommerce-banner-2.jpeg",
    is_active: true,
    is_featured: true,
    is_flash_sale: true,
    flash_sale_end: new Date(Date.now() + 86400000 * 2).toISOString(),
    rating: 4.9,
    review_count: 48,
    sales_count: 85,
    location_tag: "Islamabad",
    variants: [
      { id: "var-3", product_id: "prod-2", name: "5-in-1 Combo", attributes: { package: "5-in-1" }, price: 48000, sale_price: 41500, stock: 8, is_active: true },
      { id: "var-4", product_id: "prod-2", name: "8-in-1 Industrial", attributes: { package: "8-in-1" }, price: 62000, sale_price: 54900, stock: 4, is_active: true },
    ],
    specifications: {
      "Power": "1400W",
      "Temperature Range": "0 - 250°C",
      "Plate Size": "38cm x 38cm (15x15 Inch)",
      "Warranty": "1 Year Local Brand Warranty"
    }
  },
  {
    id: "prod-3",
    name: "5 Pcs Unisex Casual Cotton T-Shirts Pack (Summer Collection)",
    slug: "5pcs-unisex-casual-tshirts-pack",
    category_id: "cat-4",
    category_name: "Men's Fashion",
    category_slug: "mens-fashion",
    brand_name: "Karobaari Apparel",
    short_description: "100% Breathable soft cotton crew-neck everyday tees.",
    description: "High-grade combed cotton casual t-shirts featuring pre-shrunk fabric, vibrant fade-resistant colors, and tailored modern fit.",
    price: 2499,
    sale_price: 1666,
    sku: "KB-TSH-5PK",
    stock: 90,
    thumbnail_url: "/assets/ecommerce-banner-1.jpeg",
    is_active: true,
    is_featured: true,
    is_flash_sale: true,
    flash_sale_end: new Date(Date.now() + 86400000 * 2).toISOString(),
    rating: 5.0,
    review_count: 67,
    sales_count: 215,
    location_tag: "Sindh",
    variants: [
      { id: "var-5", product_id: "prod-3", name: "Medium (M) Pack", attributes: { size: "M" }, price: 2499, sale_price: 1666, stock: 40, is_active: true },
      { id: "var-6", product_id: "prod-3", name: "Large (L) Pack", attributes: { size: "L" }, price: 2499, sale_price: 1666, stock: 35, is_active: true },
      { id: "var-7", product_id: "prod-3", name: "Extra Large (XL) Pack", attributes: { size: "XL" }, price: 2699, sale_price: 1850, stock: 15, is_active: true },
    ]
  },
  {
    id: "prod-4",
    name: "Wireless Bluetooth ANC Active Noise Cancelling Earbuds",
    slug: "wireless-bluetooth-anc-earbuds",
    category_id: "cat-2",
    category_name: "Electronic Accessories",
    category_slug: "electronic-accessories",
    brand_name: "SoundHub",
    short_description: "40dB Hybrid ANC, 36-hour playback, ENC Quad-Mic crystal calls.",
    description: "Experience audiophile-grade bass and crystal clear calling with IPX5 water resistance and ultra-low latency gaming mode.",
    price: 4999,
    sale_price: 2999,
    sku: "KB-EAR-ANC",
    stock: 50,
    thumbnail_url: "/assets/ecommerce-banner-2.jpeg",
    is_active: true,
    is_featured: true,
    is_flash_sale: false,
    rating: 4.7,
    review_count: 41,
    sales_count: 180,
    location_tag: "Punjab",
  },
  {
    id: "prod-5",
    name: "Multi-Functional 12-in-1 Vegetable Chopper & Slicer",
    slug: "12-in-1-vegetable-chopper-slicer",
    category_id: "cat-7",
    category_name: "Home & Lifestyle",
    category_slug: "home-lifestyle",
    brand_name: "KitchenEase",
    short_description: "Stainless steel sharp blades with large 1.5L container.",
    description: "Save 70% preparation time in your kitchen. Chop onions, dice potatoes, grate cheese, and slice vegetables effortlessly.",
    price: 1899,
    sale_price: 1299,
    sku: "KB-KTC-CHOP",
    stock: 60,
    thumbnail_url: "/assets/ecommerce-banner-1.jpeg",
    is_active: true,
    is_featured: false,
    is_flash_sale: true,
    flash_sale_end: new Date(Date.now() + 86400000 * 2).toISOString(),
    rating: 4.6,
    review_count: 53,
    sales_count: 240,
    location_tag: "Punjab",
  },
  {
    id: "prod-6",
    name: "Smart Watch Ultra 2 with Amoled Display & Bluetooth Calling",
    slug: "smart-watch-ultra-2-amoled",
    category_id: "cat-2",
    category_name: "Electronic Accessories",
    category_slug: "electronic-accessories",
    brand_name: "Karobaari Tech",
    short_description: "Titanium alloy case, heart rate & SpO2 tracking, multiple straps included.",
    description: "Rugged military-grade smart watch with always-on AMOLED display, wireless magnetic charging, and seamless phone integration.",
    price: 7500,
    sale_price: 4899,
    sku: "KB-WTC-ULT2",
    stock: 30,
    thumbnail_url: "/assets/ecommerce-banner-2.jpeg",
    is_active: true,
    is_featured: true,
    is_flash_sale: false,
    rating: 4.9,
    review_count: 89,
    sales_count: 310,
    location_tag: "Islamabad",
  },
  {
    id: "prod-7",
    name: "Fast Charging 20000mAh Power Bank with Digital Display",
    slug: "fast-charging-20000mah-power-bank",
    category_id: "cat-1",
    category_name: "Mobiles & Tablets",
    category_slug: "mobiles-tablets",
    brand_name: "ChargeMaster",
    short_description: "22.5W PD Fast Charging, dual USB + Type-C ports, LED indicator.",
    description: "High-capacity portable battery pack designed for all Android and iOS devices. Overcharge and short-circuit protection built in.",
    price: 3999,
    sale_price: 2799,
    sku: "KB-PB-20K",
    stock: 40,
    thumbnail_url: "/assets/ecommerce-banner-1.jpeg",
    is_active: true,
    is_featured: true,
    is_flash_sale: false,
    rating: 4.8,
    review_count: 27,
    sales_count: 110,
    location_tag: "Punjab",
  },
  {
    id: "prod-8",
    name: "Premium Stitched Embroidered Lawn Suit 3-Piece Set",
    slug: "premium-stitched-embroidered-lawn-suit",
    category_id: "cat-5",
    category_name: "Women's Fashion",
    category_slug: "womens-fashion",
    brand_name: "Karobaari Couture",
    short_description: "Pure breathable lawn shirt with chiffon dupatta and dyed trousers.",
    description: "Elegant floral embroidery on luxury lawn fabric, stitched to perfection. Available in standard Pakistani sizes.",
    price: 5500,
    sale_price: 3850,
    sku: "KB-LWN-003",
    stock: 25,
    thumbnail_url: "/assets/ecommerce-banner-2.jpeg",
    is_active: true,
    is_featured: true,
    is_flash_sale: true,
    flash_sale_end: new Date(Date.now() + 86400000 * 2).toISOString(),
    rating: 4.9,
    review_count: 38,
    sales_count: 95,
    location_tag: "Punjab",
  },
];

export const initialProperties: Property[] = [
  {
    id: "prop-1",
    title: "4 Marla 1.5 Story Brand New House For Sale in Shahpur",
    slug: "4-marla-brand-new-house-shahpur",
    property_type: "House",
    status: "For Sale",
    location: "Main Stop Shahpur, Adyala Road, Rawalpindi",
    area_marla: 4.0,
    price: 12000000,
    price_display: "Rs. 1 Crore 20 Lakh",
    bedrooms: 3,
    bathrooms: 3,
    kitchens: 2,
    description: "Brand new constructed 1.5 story luxury house located in prime Shahpur on Adyala Road Rawalpindi. Premium woodwork, fall ceiling, tiles flooring, 30 ft wide paved street, sweet drinking water and direct electricity connection.",
    features: [
      "3 Spacious Bedrooms with Attached Bathrooms",
      "2 Modern Fitted Kitchens (Granite Tops)",
      "Dedicated Car Porch & Terrace",
      "Drawing / Dining Room & TV Lounge",
      "30 Feet Wide Concrete Street",
      "Sweet Water Boring & Underground Tank",
      "Electricity Meter Installed",
      "Solid A-Grade Structure & Construction"
    ],
    thumbnail_url: "/assets/real-estate-banner-1.jpeg",
    images: [
      { id: "pimg-1", public_url: "/assets/real-estate-banner-1.jpeg", alt_text: "Front Elevation" },
      { id: "pimg-2", public_url: "/assets/real-estate-banner-2.jpeg", alt_text: "Interior Model" }
    ],
    is_featured: true,
    is_active: true,
  },
  {
    id: "prop-2",
    title: "5 Marla Residential Plot in Bahria Town Phase 8",
    slug: "5-marla-plot-bahria-town-phase-8",
    property_type: "Plot",
    status: "For Sale",
    location: "Sector F, Bahria Town Phase 8, Rawalpindi",
    area_marla: 5.0,
    price: 6500000,
    price_display: "Rs. 65 Lakh",
    bedrooms: 0,
    bathrooms: 0,
    kitchens: 0,
    description: "Level plot situated in fully developed sector with immediate possession, underground utilities, parks, and 24/7 security.",
    features: [
      "Possession Ready",
      "Underground Electricity & Gas",
      "Adjacent to Commercial Hub & Mosque",
      "Gated Community Security"
    ],
    thumbnail_url: "/assets/real-estate-banner-2.jpeg",
    is_featured: true,
    is_active: true,
  },
  {
    id: "prop-3",
    title: "10 Marla Luxury Modern Villa in DHA Phase 2 Islamabad",
    slug: "10-marla-luxury-villa-dha-phase-2",
    property_type: "House",
    status: "For Sale",
    location: "Sector B, DHA Phase 2, Islamabad / Rawalpindi",
    area_marla: 10.0,
    price: 45000000,
    price_display: "Rs. 4 Crore 50 Lakh",
    bedrooms: 5,
    bathrooms: 6,
    kitchens: 2,
    description: "Designer double-unit house featuring Spanish porcelain tiles, imported sanitary fittings, automated gates, solar setup, and servant quarter.",
    features: [
      "5 Master Bedrooms with Wardrobes",
      "Double Unit (Separate Entrances)",
      "Automated Security System",
      "Spacious 2-Car Porch & Lawn"
    ],
    thumbnail_url: "/assets/real-estate-banner-1.jpeg",
    is_featured: true,
    is_active: true,
  },
  {
    id: "prop-4",
    title: "1 Kanal Commercial Plaza Plot on Main Adyala Road",
    slug: "1-kanal-commercial-plot-adyala-road",
    property_type: "Commercial",
    status: "For Sale",
    location: "Main Adyala Road, Near Ring Road Interchange, Rawalpindi",
    area_marla: 20.0,
    price: 38000000,
    price_display: "Rs. 3 Crore 80 Lakh",
    bedrooms: 0,
    bathrooms: 0,
    kitchens: 0,
    description: "High ROI commercial frontage plot ideal for shopping mall, bank branches, corporate offices or mixed-use development.",
    features: [
      "Direct Main Road Frontage (80 Ft Road)",
      "Approved for Multi-Story Commercial Construction",
      "Close Proximity to Ring Road Interchange",
      "Rapidly Developing Commercial Strip"
    ],
    thumbnail_url: "/assets/real-estate-banner-2.jpeg",
    is_featured: false,
    is_active: true,
  }
];

export const initialDigitalBooks: DigitalBook[] = [
  {
    id: "book-1",
    title: "E-Commerce Karobaar Guide — Zero to 1 Million Sales in Pakistan",
    slug: "ecommerce-karobaar-guide-pakistan",
    author: "Karobaari Hub Business Academy",
    category: "Business",
    description: "A complete step-by-step blueprint covering product sourcing in Shah Alam / Raja Bazaar, supplier negotiation, COD logistics management, and scaling Facebook/TikTok ads in Pakistan.",
    price: 1500,
    sale_price: 499,
    cover_url: "/assets/ecommerce-banner-1.jpeg",
    sample_preview_url: "#",
    file_format: "PDF",
    file_size_mb: 14.5,
    pages_count: 180,
    is_featured: true,
    is_active: true,
  },
  {
    id: "book-2",
    title: "Real Estate Investment in Rawalpindi & Islamabad Blueprint",
    slug: "real-estate-investment-rawalpindi-islamabad",
    author: "Prism Real Estate Research Wing",
    category: "Investment",
    description: "Master analysis of high-yield societies: Adyala Road expansion, Ring Road impact, DHA/Bahria trends, legal NOC verification protocols, and plot flipping strategies.",
    price: 2500,
    sale_price: 999,
    cover_url: "/assets/real-estate-banner-1.jpeg",
    sample_preview_url: "#",
    file_format: "PDF",
    file_size_mb: 22.0,
    pages_count: 240,
    is_featured: true,
    is_active: true,
  },
  {
    id: "book-3",
    title: "Modern Digital Marketing for Small Business & Freelancers",
    slug: "modern-digital-marketing-freelancers",
    author: "Syed Umair Ali",
    category: "Skill Learning",
    description: "Hands-on guide to generating high converting leads, SEO optimization, social media brand identity, and client acquisition formulas.",
    price: 1800,
    sale_price: 650,
    cover_url: "/assets/ecommerce-banner-2.jpeg",
    sample_preview_url: "#",
    file_format: "PDF",
    file_size_mb: 18.2,
    pages_count: 195,
    is_featured: false,
    is_active: true,
  }
];

export const initialCourses: Course[] = [
  {
    id: "course-1",
    title: "Mastering E-Commerce & Dropshipping in Pakistan (2026 Edition)",
    slug: "mastering-ecommerce-dropshipping-pakistan",
    short_description: "Build a profitable localized e-commerce brand with local supplier sourcing and COD courier integration.",
    description: "Comprehensive 12-hour video masterclass designed specifically for Pakistani entrepreneurs. Learn how to source winning products, build high-converting storefronts, configure Leopards/TCS/Trax APIs, and run cost-effective Meta ads.",
    instructor: "Karobaari Hub Mentorship Team",
    level: "All Levels",
    duration: "12.5 Hours",
    modules_count: 8,
    lessons_count: 42,
    price: 8000,
    sale_price: 2999,
    thumbnail_url: "/assets/ecommerce-banner-2.jpeg",
    curriculum: [
      { module_title: "Module 1: Local Market Product Research & Validation", lessons: ["Winning Product Criteria in Pakistan", "Wholesale Markets Directory (Lahore & Rawalpindi)", "Margin & ROI Calculation"] },
      { module_title: "Module 2: High Converting Storefront Setup", lessons: ["Store Design Architecture", "Mobile First Conversion Triggers", "WhatsApp Order Funnel"] },
      { module_title: "Module 3: Courier Accounts & COD Cash Flow", lessons: ["Setting Up Courier Accounts", "RTO (Return to Origin) Prevention Strategies", "Call Confirmation Systems"] },
      { module_title: "Module 4: Meta & TikTok Advertising Mastery", lessons: ["Audience Targeting for Pakistan", "Creative Formats & Urdu Copywriting", "Scaling to 100+ Orders/Day"] }
    ],
    is_featured: true,
    is_active: true,
  },
  {
    id: "course-2",
    title: "Prism Real Estate Agent & Property Investor Masterclass",
    slug: "real-estate-agent-investor-masterclass",
    short_description: "Learn property valuation, documentation verification, registry/inteqal laws and client negotiation.",
    description: "Industry insider course by certified property advisors covering residential and commercial transaction frameworks, land revenue records reading (Fard, Inteqal), and high-ticket buyer prospecting.",
    instructor: "Prism Real Estate Consultants",
    level: "Intermediate",
    duration: "16 Hours",
    modules_count: 6,
    lessons_count: 36,
    price: 15000,
    sale_price: 5999,
    thumbnail_url: "/assets/real-estate-banner-1.jpeg",
    curriculum: [
      { module_title: "Module 1: Real Estate Documentation & Legal Due Diligence", lessons: ["Understanding Fard, Inteqal & Aks Shajra", "NOC & Town Planning Approvals Verification", "Registry vs Transfer Procedures"] },
      { module_title: "Module 2: Society Analysis & Price Forecasting", lessons: ["Adyala Road & Rawalpindi Master Plan", "DHA & Bahria Town Historical Cycles", "Commercial Yield vs Capital Appreciation"] }
    ],
    is_featured: true,
    is_active: true,
  }
];

export const initialTestimonials: Testimonial[] = [
  {
    id: "test-1",
    name: "Chaudhry Tariq Mehmood",
    role: "Property Buyer, Adyala Road",
    content: "Prism Real Estate helped us secure a brand new 4 Marla house in Shahpur with 100% crystal clear documentation and zero hidden charges. Highly trustworthy team!",
    rating: 5,
    sort_order: 1,
    is_active: true,
  },
  {
    id: "test-2",
    name: "Malik Kamran",
    role: "Online Business Owner, Lahore",
    content: "Ordered the 5-in-1 sublimation heat press from Karobaari Hub. Fast delivery to Lahore in 2 days and the machine build quality is exceptional.",
    rating: 5,
    sort_order: 2,
    is_active: true,
  },
  {
    id: "test-3",
    name: "Engr. Bilal Hassan",
    role: "Investor, DHA Phase 2",
    content: "The transparency and market depth of Prism consultants is unmatched in Rawalpindi/Islamabad. Smooth deal execution.",
    rating: 5,
    sort_order: 3,
    is_active: true,
  }
];